services:
  cf-image-search:
    container_name: cf_image_search
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    restart: unless-stopped
